repos:
  - repo: https://github.com/arkinmodi/add-license-header
    rev: v2.4.1
    hooks:
      - id: add-license-header
        args:
          - --license-file
          - LICENSE-HEADER.template
          - --author-name
          - "Adityam Ghosh"
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        args: [--fix]

      - id: ruff-format
