"""make short_id unique

Revision ID: 541983dca6df
Revises: b3a6efce8fc6
Create Date: 2026-10-02 18:17:28.873633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541983dca6df'
down_revision: Union[str, Sequence[str], None] = 'b3a6efce8fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_tbl_short_id'), table_name='short_url_tbl')
    op.create_unique_constraint(None, 'short_url_tbl', ['short_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'short_url_tbl', type_='unique')
    op.create_index(op.f('ix_short_url_tbl_short_id'), 'short_url_tbl', ['short_id'], unique=False)
    # ### end Alembic commands ###
