"""initial

Revision ID: b3a6efce8fc6
Revises: 
Create Date: 2026-10-02 17:47:35.088297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a6efce8fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url_tbl',
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_tbl_id'), 'short_url_tbl', ['id'], unique=False)
    op.create_index(op.f('ix_short_url_tbl_short_id'), 'short_url_tbl', ['short_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_tbl_short_id'), table_name='short_url_tbl')
    op.drop_index(op.f('ix_short_url_tbl_id'), table_name='short_url_tbl')
    op.drop_table('short_url_tbl')
    # ### end Alembic commands ###
